[build]
  base = "Clinica Unique/"
  command = "npm run build"
  publish = "Clinica Unique/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
